name: Maven Build Workflow

on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: temurin

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Validate the project
      - name: Validate
        run: mvn validate

      # Step 4.1: Generate sources 
      - name: Generate Sources
        run: mvn generate-sources

      # Step 5: Compile the project
      - name: Compile
        run: mvn compile

      # Step 6: Set Java to Headless mode (before running tests)
      - name: Set Java to Headless mode
        run: echo "java.awt.headless=true" >> $GITHUB_ENV

      # Step 6.1: Test the project
      - name: Test
        run: mvn test

      # Step 7: Package the project
      - name: Package
        run: mvn package

      # Step 8: Verify the project
      - name: Verify
        run: mvn verify

      # Step 9: Install the project to local repository
      - name: Install
        run: mvn install
       
      # Step 10: Generate sources automatically
      - name: Generate Sources
        run: mvn generate-sources
